apiVersion: v1
kind: Service
metadata:
  name: tool-http-egress
  namespace: tardai
spec:
  type: ClusterIP
  selector:
    app: tool-http-egress
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
