apiVersion: v1
kind: Service
metadata:
  name: tool-tool-bus-introspect
  namespace: tardai
spec:
  type: ClusterIP
  selector:
    app: tool-tool-bus-introspect
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
